# Generated by Django 4.2.20 on 2025-05-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.TextField(default='no ingredients')),
                ('cooking_time', models.FloatField(help_text='in minutes')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], default='easy', max_length=20)),
            ],
        ),
    ]
